const fs = require('fs');
let content = fs.readFileSync('server.ts', 'utf8');

// Inject into approve
content = content.replace(
  `        treasuryTx.unshift({\n            id: 'TRX' + Math.floor(Math.random()*10000),\n            date: new Date(),\n            type: approval.type === 'sweep' ? 'Manual Sweep' : (approval.type === 'profit_withdrawal' ? 'Profit Withdrawal' : 'Bank Transfer'),\n            amount: approval.type === 'sweep' ? approval.metadata.amount : -approval.metadata.amount,\n            bank: approval.type === 'sweep' ? 'Internal Transfer' : (approval.metadata.bank || 'Unknown Bank')\n        });\n    }`,
  `        treasuryTx.unshift({\n            id: 'TRX' + Math.floor(Math.random()*10000),\n            date: new Date(),\n            type: approval.type === 'sweep' ? 'Manual Sweep' : (approval.type === 'profit_withdrawal' ? 'Profit Withdrawal' : 'Bank Transfer'),\n            amount: approval.type === 'sweep' ? approval.metadata.amount : -approval.metadata.amount,\n            bank: approval.type === 'sweep' ? 'Internal Transfer' : (approval.metadata.bank || 'Unknown Bank')\n        });\n    } else if (approval.type === 'esim_swap') {\n        if (useMockDb) {\n            const tx = mockTransactions.find(t => String(t._id) === String(approval.metadata.transactionId));\n            if (tx) tx.status = 'completed';\n            notifyUser(approval.metadata.userId, 'eSIM Swap Approved', \`Your request to swap \${approval.metadata.phoneNumber} to \${approval.metadata.provider} eSIM has been approved.\`);\n        } else {\n            try {\n                const tx = await Transaction.findById(approval.metadata.transactionId);\n                if (tx) {\n                    tx.status = 'completed';\n                    await tx.save();\n                }\n                notifyUser(approval.metadata.userId, 'eSIM Swap Approved', \`Your request to swap \${approval.metadata.phoneNumber} to \${approval.metadata.provider} eSIM has been approved.\`);\n            } catch (err) {}\n        }\n    }`
);

// Inject into reject
content = content.replace(
  `    if (approval.type === 'merchant_registration') {`,
  `    if (approval.type === 'esim_swap') {\n        if (useMockDb) {\n            const tx = mockTransactions.find(t => String(t._id) === String(approval.metadata.transactionId));\n            if (tx) tx.status = 'rejected';\n            const user = mockUsers.get(approval.metadata.userId);\n            if (user) user.balance += approval.amount;\n            notifyUser(approval.metadata.userId, 'eSIM Swap Rejected', \`Your request to swap \${approval.metadata.phoneNumber} to \${approval.metadata.provider} eSIM was rejected.\`);\n        } else {\n            try {\n                const tx = await Transaction.findById(approval.metadata.transactionId);\n                if (tx) {\n                    tx.status = 'rejected';\n                    await tx.save();\n                }\n                const user = await User.findById(approval.metadata.userId).catch(() => null);\n                if (user) {\n                    user.balance += approval.amount;\n                    await user.save();\n                }\n                notifyUser(approval.metadata.userId, 'eSIM Swap Rejected', \`Your request to swap \${approval.metadata.phoneNumber} to \${approval.metadata.provider} eSIM was rejected.\`);\n            } catch (err) {}\n        }\n    } else if (approval.type === 'merchant_registration') {`
);

fs.writeFileSync('server.ts', content);
