const fs = require('fs');
let content = fs.readFileSync('src/pages/Withdraw.tsx', 'utf8');

const target = "      if (parseFloat(amount) > (user?.balance || 0)) {\\n        toast.error('Insufficient balance');\\n        setError('Insufficient balance');\\n        return;\\n      }\\n\\n      setLoading(true);\\n\\n      let destination = '';\\n      if (method === 'bank') destination = `${bank} - ${bankAccount}`;\\n      else destination = `${method === 'mtn' ? 'MTN' : 'Orange'} - ${phoneNumber}`;\\n\\n      try {\\n        const res = await fetch('/api/transactions/withdraw', {\\n          method: 'POST',\\n          headers: { 'Content-Type': 'application/json' },\\n          body: JSON.stringify({\\n            userId: user?._id,\\n            amount: parseFloat(amount),\\n            bankAccount: destination\\n          })\\n        });\\n        const data = await res.json();\\n\\n        if (res.ok) {\\n          if (user) {\\n            const updatedUser = { ...user, balance: data.newBalance };\\n            setUser(updatedUser);\\n            localStorage.setItem('user', JSON.stringify(updatedUser));\\n          }\\n          setPendingWithdrawal(false);\\n          setStep(2);\\n        } else {\\n          setError(data.error || 'Withdrawal failed');\\n        }\\n      } catch (err) {\\n        setError('Failed to connect to server');\\n      } finally {\\n        setLoading(false);\\n      }\\n    }\\n  };";

const replace = "      if (parseFloat(amount) > (user?.balance || 0)) {\\n        toast.error('Insufficient balance');\\n        setError('Insufficient balance');\\n        return;\\n      }\\n\\n      // Show PIN approval modal before processing\\n      setPin('');\\n      setPinError('');\\n      setTimeLeft(60);\\n      setShowPinModal(true);\\n    }\\n  };\\n\\n  const processDirectWithdrawal = async () => {\\n    if (pin !== String(user?.pin)) {\\n      setPinError('Invalid PIN');\\n      return;\\n    }\\n    setShowPinModal(false);\\n    setLoading(true);\\n\\n    let destination = '';\\n    if (method === 'bank') destination = `${bank} - ${bankAccount}`;\\n    else destination = `${method === 'mtn' ? 'MTN' : 'Orange'} - ${phoneNumber}`;\\n\\n    try {\\n      const res = await fetch('/api/transactions/withdraw', {\\n        method: 'POST',\\n        headers: { 'Content-Type': 'application/json' },\\n        body: JSON.stringify({\\n          userId: user?._id,\\n          amount: parseFloat(amount),\\n          bankAccount: destination\\n        })\\n      });\\n      const data = await res.json();\\n\\n      if (res.ok) {\\n        if (user) {\\n          const updatedUser = { ...user, balance: data.newBalance };\\n          setUser(updatedUser);\\n          localStorage.setItem('user', JSON.stringify(updatedUser));\\n        }\\n        setPendingWithdrawal(false);\\n        setStep(2);\\n      } else {\\n        setError(data.error || 'Withdrawal failed');\\n      }\\n    } catch (err) {\\n      setError('Failed to connect to server');\\n    } finally {\\n      setLoading(false);\\n    }\\n  };";

if (content.includes(target)) {
  content = content.replace(target, replace);
  fs.writeFileSync('src/pages/Withdraw.tsx', content);
  console.log("Patched successfully!");
} else {
  console.log("Target not found!");
}
