const fs = require('fs');
let content = fs.readFileSync('server.ts', 'utf8');

content = content.replace(
  `// User gets pending withdrawals\napp.get("/api/user/:id/pending-withdrawals", async (req, res) => {\n  try {\n    let pending = [];\n    if (useMockDb) {\n      pending = mockTransactions.filter(t => String(t.userId) === String(req.params.id) && t.status === 'pending' && t.type === 'pending_withdrawal');\n    } else {\n      if (req.params.id === 'merchant1') {\n        pending = [];\n      } else {\n        pending = await Transaction.find({ userId: req.params.id, status: 'pending', type: 'pending_withdrawal' }).lean();\n      }\n      // Also add mock pending transactions in case demo merchant was used\n      const mockPending = mockTransactions.filter(t => String(t.userId) === String(req.params.id) && t.status === 'pending' && t.type === 'pending_withdrawal');\n      pending = [...pending, ...mockPending];\n    }\n    return res.json(pending.sort((a,b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()));`,
  `// User gets pending withdrawals\napp.get("/api/user/:id/pending-withdrawals", async (req, res) => {\n  try {\n    let pending = [];\n    const now = new Date().getTime();\n    if (useMockDb) {\n      pending = mockTransactions.filter(t => String(t.userId) === String(req.params.id) && t.status === 'pending' && t.type === 'pending_withdrawal');\n      // Auto-reject old transactions\n      pending.forEach(t => {\n        if (now - new Date(t.createdAt).getTime() > 5 * 60 * 1000) {\n          t.status = 'rejected';\n        }\n      });\n      pending = pending.filter(t => t.status === 'pending');\n    } else {\n      if (req.params.id === 'merchant1') {\n        pending = [];\n      } else {\n        let txs = await Transaction.find({ userId: req.params.id, status: 'pending', type: 'pending_withdrawal' });\n        // Auto-reject old transactions\n        for (let t of txs) {\n           if (now - new Date(t.createdAt).getTime() > 5 * 60 * 1000) {\n              t.status = 'rejected';\n              await t.save();\n           } else {\n              pending.push(t);\n           }\n        }\n      }\n      // Also add mock pending transactions in case demo merchant was used\n      const mockPending = mockTransactions.filter(t => String(t.userId) === String(req.params.id) && t.status === 'pending' && t.type === 'pending_withdrawal');\n      mockPending.forEach(t => {\n        if (now - new Date(t.createdAt).getTime() > 5 * 60 * 1000) {\n          t.status = 'rejected';\n        } else {\n          pending.push(t);\n        }\n      });\n    }\n    return res.json(pending.sort((a,b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()));`
);

fs.writeFileSync('server.ts', content);
