const fs = require('fs');
let content = fs.readFileSync('src/pages/Store.tsx', 'utf8');

// Replace handleEsimAction success handling
content = content.replace(
  `      if (res.ok) {\n        setQrCode(data.qrCode || 'simulated-qr-code');\n      } else {\n        alert(data.error || 'Operation failed');\n      }`,
  `      if (res.ok) {\n        if (data.pendingApproval) {\n          setPendingSwap(true);\n        } else {\n          setQrCode(data.qrCode || 'simulated-qr-code');\n          setAssignedNumber(data.newNumber || null);\n        }\n      } else {\n        alert(data.error || 'Operation failed');\n      }`
);

// Add new state variables
content = content.replace(
  `  const [qrCode, setQrCode] = useState<string | null>(null);`,
  `  const [qrCode, setQrCode] = useState<string | null>(null);\n  const [assignedNumber, setAssignedNumber] = useState<string | null>(null);\n  const [pendingSwap, setPendingSwap] = useState(false);`
);

// Add new views for pendingSwap and updated qrCode view
content = content.replace(
  `        {activeTab === 'esim' && (\n          qrCode ? (\n            <div className="bg-white dark:bg-gray-800 rounded-3xl p-8 shadow-xl text-center border border-gray-100 dark:border-gray-700 flex flex-col items-center animate-in fade-in zoom-in duration-300">\n              <div className="w-16 h-16 bg-green-100 dark:bg-green-900/30 rounded-full flex items-center justify-center mb-4">\n                <QrCode size={32} className="text-green-600 dark:text-green-400" />\n              </div>\n              <h2 className="text-2xl font-bold text-dark dark:text-white mb-2">eSIM Ready!</h2>\n              <p className="text-gray-500 dark:text-gray-400 mb-6">Scan this QR code with your phone to activate your new {provider} eSIM.</p>\n              <div className="w-48 h-48 bg-gray-100 dark:bg-gray-700 rounded-2xl border-4 border-dashed border-gray-300 dark:border-gray-500 flex items-center justify-center mb-6 relative">\n                <QrCode size={120} className="text-gray-400 dark:text-gray-500 opacity-50" />\n                <span className="absolute text-xs font-bold bg-white dark:bg-gray-800 px-2 py-1 rounded shadow-sm text-dark dark:text-white">Simulated QR</span>\n              </div>\n              <button onClick={() => setQrCode(null)} className="w-full bg-primary text-white py-4 rounded-2xl font-bold text-lg hover:bg-opacity-90 transition-all shadow-md">\n                Done\n              </button>\n            </div>\n          ) : (`,
  `        {activeTab === 'esim' && (\n          pendingSwap ? (\n            <div className="bg-white dark:bg-gray-800 rounded-3xl p-8 shadow-xl text-center border border-gray-100 dark:border-gray-700 flex flex-col items-center animate-in fade-in zoom-in duration-300">\n              <div className="w-16 h-16 bg-yellow-100 dark:bg-yellow-900/30 rounded-full flex items-center justify-center mb-4">\n                <FileText size={32} className="text-yellow-600 dark:text-yellow-400" />\n              </div>\n              <h2 className="text-2xl font-bold text-dark dark:text-white mb-2">Swap Request Pending</h2>\n              <p className="text-gray-500 dark:text-gray-400 mb-6">Your request to swap {phoneNumber} to a {provider} eSIM has been submitted and is pending provider validation.</p>\n              <button onClick={() => { setPendingSwap(false); setPhoneNumber(''); }} className="w-full bg-primary text-white py-4 rounded-2xl font-bold text-lg hover:bg-opacity-90 transition-all shadow-md">\n                Done\n              </button>\n            </div>\n          ) : qrCode ? (\n            <div className="bg-white dark:bg-gray-800 rounded-3xl p-8 shadow-xl text-center border border-gray-100 dark:border-gray-700 flex flex-col items-center animate-in fade-in zoom-in duration-300">\n              <div className="w-16 h-16 bg-green-100 dark:bg-green-900/30 rounded-full flex items-center justify-center mb-4">\n                <QrCode size={32} className="text-green-600 dark:text-green-400" />\n              </div>\n              <h2 className="text-2xl font-bold text-dark dark:text-white mb-2">eSIM Ready!</h2>\n              <p className="text-gray-500 dark:text-gray-400 mb-2">Scan this QR code with your phone to activate your new {provider} eSIM.</p>\n              {assignedNumber && <p className="text-lg font-bold text-primary mb-6">New Number: {assignedNumber}</p>}\n              <div className="w-48 h-48 bg-gray-100 dark:bg-gray-700 rounded-2xl border-4 border-dashed border-gray-300 dark:border-gray-500 flex items-center justify-center mb-6 relative">\n                <QrCode size={120} className="text-gray-400 dark:text-gray-500 opacity-50" />\n                <span className="absolute text-xs font-bold bg-white dark:bg-gray-800 px-2 py-1 rounded shadow-sm text-dark dark:text-white">Simulated QR</span>\n              </div>\n              <button onClick={() => { setQrCode(null); setAssignedNumber(null); }} className="w-full bg-primary text-white py-4 rounded-2xl font-bold text-lg hover:bg-opacity-90 transition-all shadow-md">\n                Done\n              </button>\n            </div>\n          ) : (`
);

fs.writeFileSync('src/pages/Store.tsx', content);
